"""产品档案表"""

from datetime import date, datetime
from sqlalchemy import String, Integer, BigInteger, Float, Boolean, Date, DateTime, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Product(Base):
    __tablename__ = "products"

    asin: Mapped[str] = mapped_column(String(20), primary_key=True, comment="ASIN编码")
    # ── 身份标识 ──
    lx_id: Mapped[int | None] = mapped_column(BigInteger, comment="领星商品ID")
    store_id: Mapped[int | None] = mapped_column(Integer, comment="店铺ID")
    msku: Mapped[str | None] = mapped_column(String(100), comment="MSKU")
    local_sku: Mapped[str | None] = mapped_column(String(100), comment="本地SKU")
    fnsku: Mapped[str | None] = mapped_column(String(30), comment="FNSKU")
    mid: Mapped[str | None] = mapped_column(String(100), comment="站点ID(mid)")
    amz_product_id: Mapped[str | None] = mapped_column(String(100), comment="亚马逊商品ID")
    amz_product_id_type_text: Mapped[str | None] = mapped_column(String(50), comment="亚马逊商品ID类型")
    parent_asin: Mapped[str | None] = mapped_column(String(20), comment="变体父体ASIN")
    product_id: Mapped[str | None] = mapped_column(String(100), comment="产品ID")
    product_relation_id: Mapped[str | None] = mapped_column(String(100), comment="款名/SPU关联ID")
    id_hash: Mapped[str | None] = mapped_column(String(100), comment="ID哈希")
    # ── 名称与描述 ──
    product_name: Mapped[str] = mapped_column(Text, nullable=False, comment="产品名称")
    listing_title: Mapped[str | None] = mapped_column(Text, comment="亚马逊标题(item_name)")
    local_name: Mapped[str | None] = mapped_column(Text, comment="内部品名(local_name)")
    model: Mapped[str | None] = mapped_column(String(100), comment="型号")
    variant: Mapped[str | None] = mapped_column(Text, comment="变体")
    variant_text: Mapped[str | None] = mapped_column(Text, comment="变体文本")
    remark: Mapped[str | None] = mapped_column(Text, comment="备注")
    amz_product_type: Mapped[str | None] = mapped_column(String(100), comment="亚马逊产品类型")
    # ── 价格与费用 ──
    price: Mapped[str | None] = mapped_column(String(30), comment="售价")
    listing_price: Mapped[str | None] = mapped_column(String(30), comment="Listing价")
    landed_price: Mapped[str | None] = mapped_column(String(30), comment="落地价")
    regular_price: Mapped[str | None] = mapped_column(String(30), comment="日常价")
    list_price: Mapped[str | None] = mapped_column(String(30), comment="目录价")
    b2b_price: Mapped[str | None] = mapped_column(String(30), comment="B2B价")
    b2b_price_discount: Mapped[str | None] = mapped_column(Text, comment="B2B折扣")
    fba_fee: Mapped[str | None] = mapped_column(String(30), comment="FBA费用")
    report_fba_fee: Mapped[str | None] = mapped_column(String(30), comment="报表FBA费用")
    referral_fee: Mapped[str | None] = mapped_column(String(30), comment="佣金")
    shipping: Mapped[str | None] = mapped_column(String(30), comment="运费")
    points: Mapped[str | None] = mapped_column(String(30), comment="积分")
    history_price: Mapped[str | None] = mapped_column(String(30), comment="历史价格")
    history_price_source: Mapped[str | None] = mapped_column(String(100), comment="历史价格来源")
    currency_symbol: Mapped[str | None] = mapped_column(String(10), comment="货币符号")
    # ── 销量与销售额 ──
    total_volume: Mapped[int | None] = mapped_column(BigInteger, comment="历史总销量")
    yesterday_volume: Mapped[int | None] = mapped_column(Integer, comment="昨日销量")
    seven_volume: Mapped[int | None] = mapped_column(Integer, comment="7天销量")
    fourteen_volume: Mapped[int | None] = mapped_column(Integer, comment="14天销量")
    thirty_volume: Mapped[int | None] = mapped_column(Integer, comment="30天销量")
    average_seven_volume: Mapped[float | None] = mapped_column(Float, comment="7天日均销量")
    average_fourteen_volume: Mapped[float | None] = mapped_column(Float, comment="14天日均销量")
    average_thirty_volume: Mapped[float | None] = mapped_column(Float, comment="30天日均销量")
    yesterday_amount: Mapped[float | None] = mapped_column(Float, comment="昨日销售额")
    seven_amount: Mapped[float | None] = mapped_column(Float, comment="7天销售额")
    fourteen_amount: Mapped[float | None] = mapped_column(Float, comment="14天销售额")
    thirty_amount: Mapped[float | None] = mapped_column(Float, comment="30天销售额")
    # ── 广告花费 ──
    yesterday_spend: Mapped[float | None] = mapped_column(Float, comment="昨日广告花费")
    seven_spend: Mapped[float | None] = mapped_column(Float, comment="7天广告花费")
    fourteen_spend: Mapped[float | None] = mapped_column(Float, comment="14天广告花费")
    thirty_spend: Mapped[float | None] = mapped_column(Float, comment="30天广告花费")
    # ── 库存（FBA） ──
    afn_fulfillable_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA可售")
    afn_reserved_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA预留")
    reserved_fc_transfers: Mapped[int | None] = mapped_column(Integer, comment="待调仓")
    reserved_fc_processing: Mapped[int | None] = mapped_column(Integer, comment="调仓中")
    reserved_customerorders: Mapped[int | None] = mapped_column(Integer, comment="客户订单预留")
    afn_inbound_shipped_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA在途")
    afn_unsellable_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA不可售")
    afn_inbound_working_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA入库中")
    afn_inbound_receiving_quantity: Mapped[int | None] = mapped_column(Integer, comment="FBA待发货")
    quantity: Mapped[int | None] = mapped_column(Integer, comment="当前数量")
    # ── 领星补货口径（每日同步写回基础数据，分析直接用最新值，不再依赖旧快照） ──
    fba_available_days: Mapped[int | None] = mapped_column(Integer, comment="领星可售天数")
    stockout_date: Mapped[date | None] = mapped_column(Date, comment="领星预计售罄日")
    estimated_daily_sales: Mapped[float | None] = mapped_column(Float, comment="领星预估日均销量")
    purchase_on_order: Mapped[int | None] = mapped_column(Integer, comment="待到货量(采购单)")
    # ── 排名与表现 ──
    rank: Mapped[int | None] = mapped_column(Integer, comment="大类排名")
    seller_rank: Mapped[int | None] = mapped_column(Integer, comment="卖家排名")
    category_rank: Mapped[str | None] = mapped_column(Text, comment="类目排名JSON")
    small_rank: Mapped[str | None] = mapped_column(Text, comment="小类排名JSON")
    seller_category: Mapped[str | None] = mapped_column(String(200), comment="卖家类目")
    category_url: Mapped[str | None] = mapped_column(Text, comment="类目链接")
    stars: Mapped[float | None] = mapped_column(Float, comment="评分")
    reviews_num: Mapped[int | None] = mapped_column(Integer, comment="评论数")
    # ── 时间字段 ──
    open_date_time: Mapped[str | None] = mapped_column(String(50), comment="上架时间原始值")
    first_order_time: Mapped[str | None] = mapped_column(String(50), comment="首单时间")
    first_order_type: Mapped[str | None] = mapped_column(String(50), comment="首单类型")
    first_order_update: Mapped[str | None] = mapped_column(String(50), comment="首单更新时间")
    on_sale_time: Mapped[str | None] = mapped_column(String(50), comment="上架/开售时间")
    create_time: Mapped[str | None] = mapped_column(String(50), comment="创建时间(原始)")
    update_time: Mapped[str | None] = mapped_column(String(50), comment="更新时间(原始)")
    # ── 分类与品牌 ──
    category_id: Mapped[int | None] = mapped_column(BigInteger, comment="领星分类ID")
    brand_id: Mapped[int | None] = mapped_column(BigInteger, comment="品牌ID")
    brand_name: Mapped[str | None] = mapped_column(String(100), comment="品牌名")
    brand: Mapped[str | None] = mapped_column(String(100), comment="品牌")
    category: Mapped[str | None] = mapped_column(String(100), comment="产品分类（如：毛毡类）")
    sub_category: Mapped[str | None] = mapped_column(String(50), comment="子分类（装饰品/非装饰品）")
    # ── 店铺与运营 ──
    shop: Mapped[str | None] = mapped_column(String(100), comment="店铺")
    marketplace: Mapped[str | None] = mapped_column(String(50), comment="国家/站点")
    seller_name: Mapped[str | None] = mapped_column(String(100), comment="卖家名称")
    store_type: Mapped[str | None] = mapped_column(String(20), comment="店铺类型")
    fulfillment_channel_type: Mapped[str | None] = mapped_column(String(20), comment="配送渠道(FBA)")
    status_text: Mapped[str | None] = mapped_column(String(20), comment="状态文本(在售)")
    is_delete: Mapped[str | None] = mapped_column(String(5), comment="是否删除")
    principal_list: Mapped[str | None] = mapped_column(Text, comment="负责人列表JSON")
    principal_uids: Mapped[str | None] = mapped_column(Text, comment="负责人UID列表JSON")
    permission_user_info: Mapped[str | None] = mapped_column(Text, comment="权限用户JSON")
    product_creator_realname: Mapped[str | None] = mapped_column(String(100), comment="创建人")
    product_developer: Mapped[str | None] = mapped_column(String(100), comment="开发人")
    icon: Mapped[str | None] = mapped_column(Text, comment="图标URL")
    # ── 标签与采购档案 ──
    tags: Mapped[str | None] = mapped_column(Text, comment="标签JSON(tagName列表)")
    supplier_name: Mapped[str | None] = mapped_column(String(100), comment="供应商")
    cost_price: Mapped[str | None] = mapped_column(String(30), comment="采购报价(cg_price)")
    acos_30d: Mapped[float | None] = mapped_column(Float, comment="30天广告ACOS（新品硬性指标，可手动填写）")
    # ── 业务维护字段 ──
    life_cycle: Mapped[str | None] = mapped_column(String(20), comment="生命周期阶段")
    product_level: Mapped[str | None] = mapped_column(String(5), comment="产品等级 S/A/B/C/D")
    calc_frequency: Mapped[str | None] = mapped_column(String(5), comment="计算频率 P0/P1/P2/P3/P4")
    product_type: Mapped[str | None] = mapped_column(String(20), comment="节日产品/长期产品")
    product_stage: Mapped[str | None] = mapped_column(String(10), comment="新品/老品")
    festival: Mapped[str | None] = mapped_column(String(50), comment="所属节日")
    core_months: Mapped[str | None] = mapped_column(Text, comment="核心销售月份 JSON数组 [8,9,10,11,12]")
    lead_time: Mapped[int | None] = mapped_column(Integer, comment="工期(天)")
    box_quantity: Mapped[int | None] = mapped_column(Integer, comment="单箱数量")
    length_cm: Mapped[float | None] = mapped_column(Float, comment="包装长(cm, 领星cg_package_length)")
    width_cm: Mapped[float | None] = mapped_column(Float, comment="包装宽(cm, 领星cg_package_width)")
    height_cm: Mapped[float | None] = mapped_column(Float, comment="包装高(cm, 领星cg_package_height)")
    weight_kg: Mapped[float | None] = mapped_column(Float, comment="毛重(kg, 领星cg_product_gross_weight/1000)")
    min_order_qty: Mapped[int | None] = mapped_column(Integer, comment="最低采购量")
    list_date: Mapped[date | None] = mapped_column(Date, comment="上架日期")
    status: Mapped[bool] = mapped_column(Boolean, default=True, comment="启用/停用")
    operator: Mapped[str | None] = mapped_column(Text, comment="负责运营（多个用逗号分隔）")
    primary_operator: Mapped[str | None] = mapped_column(String(100), comment="主运营负责人（从负责人列表匹配运营人员，优先显示）")
    is_new: Mapped[bool] = mapped_column(Boolean, default=False, comment="是否新品(product_stage=新品)")
    profit_rate: Mapped[float | None] = mapped_column(comment="利润率")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, comment="创建时间")
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, onupdate=datetime.now, comment="更新时间")
